# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    paralellism: 1
    steps:
      - checkout
      - run: mvn test
      - store_artifacts:
        path:  target